### ISSUE TITLE
[ops] alerting based on logs

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-identite#107]
- user is spamming
- java error

**Comment by mcalinghee** [comment]
Commentaire de @pli01 :
Vous pouvez utiliser le sentry mutualisé de beta (utilisé par les startups d état) , mais faut garder a l esprit qu il est mutualisé
(donc gaffes aux secret,  identifiant et niveau d homologation autorisé )
Pour tchap, on peut faire la demande d achat d un sentry dédié, mais il ne sera pas dans le cloud de l état....

Pour demander l ajout des projet sentry , Sur le mattermost de beta : incubateur-demandes-ops , y  a un formulaire  et on lancera le chatbot pour creer les projets
