### ISSUE TITLE
Automatiser la création / mise à jour de la license

### ISSUE THREAD

**Issue by celiacheff** [tchapgouv/tchap-identite#122]
Related to #63 
Actuellement je gère les copyright grâce à mon IDE. Julien suggère d'automatiser le process de création à l'ajout d'un nouveau fichier et éventuellement mise à jour de tous les copyright au besoin. 
Suggestions et remarques bienvenues

**Comment by odelcroi** [comment]
Nous utilisons spotless qui se charge :
- verifier le format du code. `spotless check`
- appliquer le formating du code `spotless apply`
- de remplir les headers de license par la même occasion

**Comment by celiacheff** [comment]
Solved by #63
