### ISSUE TITLE
Formatter le code otp

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-identite#14]
Selon les études : 

Le **code** doit être facile à mémoriser (mémoire de travail).

- Le format de code le plus facile à traiter est de ****6 éléments par groupes de 3 séparés par un espace. Les chiffres sont les plus faciles.
- Si on utilise des lettres, les avoir en minuscules, par groupes de 3 séparés par un espace.
- Eviter le mélange chiffres, lettres minuscules et majuscules, parce que c’est la porte ouverte aux erreurs.

**Comment by estellecomment** [comment]
@Caroline-lawson
