### ISSUE TITLE
Implémenter Bot OTP Tchap en Java

### ISSUE THREAD

**Issue by celiacheff** [tchapgouv/tchap-identite#4]
Note; le chiffrement est optionnel.
- [x] Choix de la librairie (a priori celle d'Android) -> Non, pas compatible
- [x] Demander à l'équipe Android un bout de code pour la création d'un DM

Errors
- [ ] Documentate FeignRuntime Exception

Flow Bot

- [ ] Vérifier si un DM existe entre la cible et le bot
- [ ] Si oui, récupérer et envoyer l'OTP la-bas
- [ ] Si non, créer un DM et envoyer l'OTP
- [x] Générifier le sendOTP pour tout message

# Cas à gérer
- [x] Le bot et l'utilisateur n'ont aucun salon
- [x] Le bot et l'utilisateur ont un salon et l'utilisateur est encore dans le salon
- [ ] Le bot et l'utilisateur ont un salon et l'utilisateur est parti du salon
- [ ] Le bot et l'utilisateur ont un salon et l'utilisateur n'a pas encore accepté d'invitation précédente
- [ ] Le bot et l'utilisateur ont un salon et l'utilisateur à rejeté l'invitation

# Idées
- [ ] Possibilité intéressante de Maghen: Supprimer dans la table DMRoom dès l'envoi du DM, afin d'éviter plusieurs problèmes. EDIT: Lesquels? 
- [ ] Utiliser une table de KC pour stocker les liens DM EDIT: pour quels avantages?

**Comment by jdauphant** [comment]
I have switch to P2, production of what we already got is more interesting

**Comment by jdauphant** [comment]
@giomfo c'est le start dm mais côté Bot. On peut avoir l'algo ?

**Comment by giomfo** [comment]
il me semble que vous n'avez plus besoin ;)
