### ISSUE TITLE
Supprimer la mention de Tchap dans l'email "Tchap Identité"

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-identite#68]
![image](https://user-images.githubusercontent.com/1238254/173398798-24c8a8fd-860c-4247-bb78-38348e587bb2.png)
Supprimer la mention "AudioConf utilise Tchap pour assurer que seuls les agents publics", ce n'est pas le cas du coup.

cc @Caroline-lawson

**Comment by Caroline-lawson** [comment]
Pas sûre de comprendre ? 

@jdauphant

**Comment by jdauphant** [comment]
Mon hypothèse est que cette information est ambigu pour l'utilisateur. Pourquoi on parlerait de Tchap dans cette email ?

Je propose de supprimer la mention complète.
