### ISSUE TITLE
[ux] home page keycloak

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-identite#69]
# Problem
https://app.authentification.beta.gouv.fr/ shows keycloak landing page
<img width="880" alt="image" src="https://user-images.githubusercontent.com/4077729/173517270-a5302f23-1d05-4ff8-a1d4-57a1289df94a.png">

# Solution 
Create a proper login page : we can show a list of clients that can connect with this server

# Alternative solution
Temporary redirect to audioconf FAQ where we explain the new auth system

**Comment by odelcroi** [comment]
redirect vers la page startup de Authentification

**Comment by areox-net** [comment]
I'm not sure to understand what's the use of this page fo the users. 
Do we need it at this stage? The redirect to the FAQ seems enough for the moment. But I may be missing something.

**Comment by odelcroi** [comment]
> The redirect to the FAQ seems enough for the moment. But I may be missing something.


Yes
