### ISSUE TITLE
Improve Tchap OTP bot and flow

### ISSUE THREAD

**Issue by celiacheff** [tchapgouv/tchap-identite#85]
Follows 

- [ ] More unit and integration tests.
- [ ] Encryption: #80 
- [x] #81 
- [ ] https://github.com/tchapgouv/tchap-identite/issues/79
- [x] https://github.com/tchapgouv/tchap-identite/issues/78

# Errors
- [ ] Documentate FeignRuntime Exception

# Cas à gérer
- [x] Le bot et l'utilisateur n'ont aucun salon
- [x] Le bot et l'utilisateur ont un salon et l'utilisateur est encore dans le salon
- [ ] #96
- [ ] #97
- [x] #98

**Comment by odelcroi** [comment]
Faire un prototype d'envoi de message chiffré : https://gitlab.com/trixnity/trixnity

**Comment by odelcroi** [comment]
closed as inner tickets are created
