### ISSUE TITLE
[ux] Refreshing the "Input code" page sends a new code

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-identite#86]
Reproduce 
 - "reserver une conference", you are redirected on the auth page, where you should enter the code.
 - refresh the page.
 Obtained : a new code is sent by email. (the previous code is invalidated, which is good)
 Expected : As a user, the action that sends the code is the click on "Reserver la conf". It's strange that refreshing the code page resends a code.

**Comment by odelcroi** [comment]
This behaviour is a side effect of keycloak. When refreshing the page, it creates a new authenticate session which is parallel to the previous one. 

It happens also if the user press "back" and "forward" in its browser history.

What strikes me most here,  is that there is no feedback to the user that a code has been sent. 

On the other hand, there is an issue #17  to add a button to explicity send a new code and study the question to prevent spamming code by setting a cooldown time

**Comment by estellecomment** [comment]
> What strikes me most here, is that there is no feedback to the user that a code has been sent.

True ! Since this is not really a bug, displaying "A new code has been sent" could be a "fix".

In terms of UI components, Audioconf has flash messages ([example](https://github.com/betagouv/audioconf/blob/d8c74c2703dbc40a25f4107927116e6f644d31b1/controllers/createConfController.js#L56)) which we could use to easily display this.

**Comment by areox-net** [comment]
I agree with @estellecomment. A flash message notification could do the trick in both cases: a page refresh, the user clicks on "send a new code"

**Comment by odelcroi** [comment]
A la premiere connection : 
![Capture d’écran 2022-06-27 à 11 43 08](https://user-images.githubusercontent.com/4077729/175911661-a100d6bd-23af-4f92-bee0-6160523d6c85.png)

Si l'utilisateur fait un refresh ou une refait une demande 
![Capture d’écran 2022-06-27 à 11 43 17](https://user-images.githubusercontent.com/4077729/175912014-0acce12e-484f-436b-b419-b39bf7667265.png)

**Comment by areox-net** [comment]
Ca passe assez bien. Il faudrait juste ajouter une margin-bottom au message pour qu'il soit séparé du titre de la page.
